num_workers: 5

patience: 5
early_stopping_criterion:
    - valid
    - acc
    - max

# network architecture
# encoder related
encoder: rnn
encoder_conf:
    rnn_type: lstm     # encoder architecture type
    bidirectional: True
    use_projection: True
    num_layers: 4
    hidden_size: 1024
    output_size: 1024
    dropout: 0.1
    
# decoder related
decoder: rnn
decoder_conf:
    rnn_type: lstm
    num_layers: 2
    hidden_size: 1024
    sampling_probability: 0
    dropout: 0.1
    att_conf:
        atype: location
        adim: 512
        aconv_chans: 10
        aconv_filts: 100

# hybrid CTC/attention
model_conf:
    ctc_weight: 0.5

val_scheduler_criterion:
- valid
- loss
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 5
scheduler: reducelronplateau
scheduler_conf:
        mode: min
        factor: 0.5
        patience : 1

# optimization related
optim: adadelta
optim_conf:
    lr: 1.0
    rho: 0.95
    eps: 1.0e-08
    weight_decay: 0
init: xavier_uniform
max_epoch: 50

# minibatch related
batch_type: folded
batch_size: 40

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2